# Generated by Django 3.1.1 on 2020-12-19 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
    ]
