# Generated by Django 3.1.1 on 2020-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201219_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
